/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiAxelChatRouteImport } from './routes/api/axel-chat'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesTeamRouteImport } from './routes/_authenticated/sales-team'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPlanComptableRouteImport } from './routes/_authenticated/plan-comptable'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedGrandLivreRouteImport } from './routes/_authenticated/grand-livre'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedCompteResultatRouteImport } from './routes/_authenticated/compte-resultat'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedBilanRouteImport } from './routes/_authenticated/bilan'
import { Route as AuthenticatedBalanceRouteImport } from './routes/_authenticated/balance'
import { Route as AuthenticatedAxelRouteImport } from './routes/_authenticated/axel'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAxelIndexRouteImport } from './routes/_authenticated/axel.index'
import { Route as AuthenticatedAxelThreadIdRouteImport } from './routes/_authenticated/axel.$threadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAxelChatRoute = ApiAxelChatRouteImport.update({
  id: '/api/axel-chat',
  path: '/api/axel-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesTeamRoute = AuthenticatedSalesTeamRouteImport.update({
  id: '/sales-team',
  path: '/sales-team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanComptableRoute =
  AuthenticatedPlanComptableRouteImport.update({
    id: '/plan-comptable',
    path: '/plan-comptable',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrandLivreRoute = AuthenticatedGrandLivreRouteImport.update({
  id: '/grand-livre',
  path: '/grand-livre',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompteResultatRoute =
  AuthenticatedCompteResultatRouteImport.update({
    id: '/compte-resultat',
    path: '/compte-resultat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBilanRoute = AuthenticatedBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAxelRoute = AuthenticatedAxelRouteImport.update({
  id: '/axel',
  path: '/axel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAxelIndexRoute = AuthenticatedAxelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAxelRoute,
} as any)
const AuthenticatedAxelThreadIdRoute =
  AuthenticatedAxelThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAxelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/axel': typeof AuthenticatedAxelRouteWithChildren
  '/balance': typeof AuthenticatedBalanceRoute
  '/bilan': typeof AuthenticatedBilanRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/compte-resultat': typeof AuthenticatedCompteResultatRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/grand-livre': typeof AuthenticatedGrandLivreRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/plan-comptable': typeof AuthenticatedPlanComptableRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-team': typeof AuthenticatedSalesTeamRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/axel-chat': typeof ApiAxelChatRoute
  '/axel/$threadId': typeof AuthenticatedAxelThreadIdRoute
  '/axel/': typeof AuthenticatedAxelIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/bilan': typeof AuthenticatedBilanRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/compte-resultat': typeof AuthenticatedCompteResultatRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/grand-livre': typeof AuthenticatedGrandLivreRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/plan-comptable': typeof AuthenticatedPlanComptableRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-team': typeof AuthenticatedSalesTeamRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/axel-chat': typeof ApiAxelChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/axel/$threadId': typeof AuthenticatedAxelThreadIdRoute
  '/axel': typeof AuthenticatedAxelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/axel': typeof AuthenticatedAxelRouteWithChildren
  '/_authenticated/balance': typeof AuthenticatedBalanceRoute
  '/_authenticated/bilan': typeof AuthenticatedBilanRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/compte-resultat': typeof AuthenticatedCompteResultatRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/grand-livre': typeof AuthenticatedGrandLivreRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/plan-comptable': typeof AuthenticatedPlanComptableRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales-team': typeof AuthenticatedSalesTeamRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/axel-chat': typeof ApiAxelChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/axel/$threadId': typeof AuthenticatedAxelThreadIdRoute
  '/_authenticated/axel/': typeof AuthenticatedAxelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/axel'
    | '/balance'
    | '/bilan'
    | '/budgets'
    | '/clients'
    | '/companies'
    | '/compte-resultat'
    | '/expenses'
    | '/grand-livre'
    | '/invoices'
    | '/journal'
    | '/pipeline'
    | '/plan-comptable'
    | '/projects'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/sales-team'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/transactions'
    | '/api/axel-chat'
    | '/axel/$threadId'
    | '/axel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/balance'
    | '/bilan'
    | '/budgets'
    | '/clients'
    | '/companies'
    | '/compte-resultat'
    | '/expenses'
    | '/grand-livre'
    | '/invoices'
    | '/journal'
    | '/pipeline'
    | '/plan-comptable'
    | '/projects'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/sales-team'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/transactions'
    | '/api/axel-chat'
    | '/'
    | '/axel/$threadId'
    | '/axel'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/axel'
    | '/_authenticated/balance'
    | '/_authenticated/bilan'
    | '/_authenticated/budgets'
    | '/_authenticated/clients'
    | '/_authenticated/companies'
    | '/_authenticated/compte-resultat'
    | '/_authenticated/expenses'
    | '/_authenticated/grand-livre'
    | '/_authenticated/invoices'
    | '/_authenticated/journal'
    | '/_authenticated/pipeline'
    | '/_authenticated/plan-comptable'
    | '/_authenticated/projects'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/quotations'
    | '/_authenticated/reports'
    | '/_authenticated/sales-team'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/team'
    | '/_authenticated/transactions'
    | '/api/axel-chat'
    | '/_authenticated/'
    | '/_authenticated/axel/$threadId'
    | '/_authenticated/axel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAxelChatRoute: typeof ApiAxelChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/axel-chat': {
      id: '/api/axel-chat'
      path: '/api/axel-chat'
      fullPath: '/api/axel-chat'
      preLoaderRoute: typeof ApiAxelChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-team': {
      id: '/_authenticated/sales-team'
      path: '/sales-team'
      fullPath: '/sales-team'
      preLoaderRoute: typeof AuthenticatedSalesTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan-comptable': {
      id: '/_authenticated/plan-comptable'
      path: '/plan-comptable'
      fullPath: '/plan-comptable'
      preLoaderRoute: typeof AuthenticatedPlanComptableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grand-livre': {
      id: '/_authenticated/grand-livre'
      path: '/grand-livre'
      fullPath: '/grand-livre'
      preLoaderRoute: typeof AuthenticatedGrandLivreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compte-resultat': {
      id: '/_authenticated/compte-resultat'
      path: '/compte-resultat'
      fullPath: '/compte-resultat'
      preLoaderRoute: typeof AuthenticatedCompteResultatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bilan': {
      id: '/_authenticated/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof AuthenticatedBilanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/axel': {
      id: '/_authenticated/axel'
      path: '/axel'
      fullPath: '/axel'
      preLoaderRoute: typeof AuthenticatedAxelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/axel/': {
      id: '/_authenticated/axel/'
      path: '/'
      fullPath: '/axel/'
      preLoaderRoute: typeof AuthenticatedAxelIndexRouteImport
      parentRoute: typeof AuthenticatedAxelRoute
    }
    '/_authenticated/axel/$threadId': {
      id: '/_authenticated/axel/$threadId'
      path: '/$threadId'
      fullPath: '/axel/$threadId'
      preLoaderRoute: typeof AuthenticatedAxelThreadIdRouteImport
      parentRoute: typeof AuthenticatedAxelRoute
    }
  }
}

interface AuthenticatedAxelRouteChildren {
  AuthenticatedAxelThreadIdRoute: typeof AuthenticatedAxelThreadIdRoute
  AuthenticatedAxelIndexRoute: typeof AuthenticatedAxelIndexRoute
}

const AuthenticatedAxelRouteChildren: AuthenticatedAxelRouteChildren = {
  AuthenticatedAxelThreadIdRoute: AuthenticatedAxelThreadIdRoute,
  AuthenticatedAxelIndexRoute: AuthenticatedAxelIndexRoute,
}

const AuthenticatedAxelRouteWithChildren =
  AuthenticatedAxelRoute._addFileChildren(AuthenticatedAxelRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAxelRoute: typeof AuthenticatedAxelRouteWithChildren
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRoute
  AuthenticatedBilanRoute: typeof AuthenticatedBilanRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedCompteResultatRoute: typeof AuthenticatedCompteResultatRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGrandLivreRoute: typeof AuthenticatedGrandLivreRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPlanComptableRoute: typeof AuthenticatedPlanComptableRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesTeamRoute: typeof AuthenticatedSalesTeamRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAxelRoute: AuthenticatedAxelRouteWithChildren,
  AuthenticatedBalanceRoute: AuthenticatedBalanceRoute,
  AuthenticatedBilanRoute: AuthenticatedBilanRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedCompteResultatRoute: AuthenticatedCompteResultatRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGrandLivreRoute: AuthenticatedGrandLivreRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPlanComptableRoute: AuthenticatedPlanComptableRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesTeamRoute: AuthenticatedSalesTeamRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAxelChatRoute: ApiAxelChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
